title: Accounts Payable Analytics
description: Analytical dashboards and reports focused on the Accounts Payable department.
baseurl: "/accounts-payable-analytics"
url: "https://marcin-charzynski.github.io"
plugins:
  - jekyll-remote-theme
remote_theme: Marcin-Charzynski/marcin-charzynski.github.io
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    line_numbers: true
