title: Accounts Payable Analytics
description: Analytical dashboards and reports focused on the Accounts Payable department.
baseurl: "/accounts-payable-analytics"
url: "https://marcin-charzynski.github.io"
theme: minima
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    line_numbers: true
